"use server";

import type { PostgrestError } from "@supabase/supabase-js";
import { revalidatePath } from "next/cache";
import { z } from "zod";

import type { ActionResult } from "@/app/actions/auth";
import { createClient } from "@/lib/supabase/server";
import {
  shipmentIdSchema,
  shipmentSchema,
  type ShipmentInput,
} from "@/lib/validations/shipment";
import type { Shipment } from "@/types/database";

/**
 * Re-exported so the client form types its action results without reaching into
 * the auth module. This is `export type`, not `export {}`: it is erased at
 * compile time, so this file still emits nothing but async functions, which is
 * the only thing a `"use server"` module is allowed to export.
 */
export type { ActionResult } from "@/app/actions/auth";

const SHIPMENTS_PATH = "/embarques";

const UNAUTHORIZED_ERROR = "No tenés autorización para realizar esta operación.";
const INVALID_INPUT_ERROR = "Revisá los datos ingresados.";
const MUTATION_FAILED_ERROR = "No pudimos guardar el embarque. Intentá de nuevo.";

/**
 * `shipments.reference` is `text not null unique`, so Postgres answers a
 * collision with `23505`. It is the only unique constraint reachable from these
 * actions — `id` is generated by the database and `reference` is the sole
 * business key — so one message covers both the create and the update case.
 * Editing a shipment onto a reference another shipment already owns is a normal
 * mistake, not an edge case, and gets its own wording instead of the generic
 * "no pudimos guardar".
 */
const REFERENCE_TAKEN_ERROR = "Ya existe un embarque con esa referencia.";

/**
 * `client_id` references `clients (id)` with `ON DELETE NO ACTION`, so a
 * client that no longer exists fails the write with `23503`. It is the only
 * foreign key on the table, so the code identifies the cause unambiguously.
 */
const CLIENT_MISSING_ERROR = "El cliente seleccionado no existe.";

/** `.eq("id", ...)` matched no row: the shipment was deleted after it rendered. */
const SHIPMENT_NOT_FOUND_ERROR =
  "El embarque que estás editando ya no existe. Actualizá la página e intentá de nuevo.";

const DELETE_NOT_FOUND_ERROR =
  "El embarque que intentás eliminar ya no existe. Actualizá la página e intentá de nuevo.";

/**
 * Postgres/PostgREST status codes mapped to UI copy.
 *
 * Only the *code* is inspected, never the message: Supabase error strings are
 * English, can name internal details (constraint names, RLS policy names) and are
 * never valid UI copy. Anything unmapped falls back to a generic message rather
 * than leaking the raw error.
 */
const SUPABASE_ERROR_MESSAGES: Record<string, string> = {
  "23502": "Faltan datos obligatorios para guardar el embarque.",
  "23503": CLIENT_MISSING_ERROR,
  "23505": REFERENCE_TAKEN_ERROR,
  "23514": "Los datos ingresados no cumplen las condiciones del sistema.",
  "42501": UNAUTHORIZED_ERROR,
};

function mutationError(error: PostgrestError): string {
  return SUPABASE_ERROR_MESSAGES[error.code] ?? MUTATION_FAILED_ERROR;
}

/**
 * `z.flattenError` (zod v4) types `fieldErrors` as `{ [field]?: string[] }`:
 * optional keys, which under `strict` is not assignable to the
 * `Record<string, string[]>` that `ActionResult` declares. The single assertion
 * below widens that mapped type to a lookup table so it can be iterated at all —
 * without it `Object.entries` cannot infer through a mapped type over an
 * unresolved generic. Fields with no issue are then dropped rather than emitted
 * as `undefined`, so callers can read `fieldErrors.reference?.[0]` directly.
 */
function toFieldErrors<T>(error: z.ZodError<T>): Record<string, string[]> {
  const { fieldErrors } = z.flattenError(error);
  const result: Record<string, string[]> = {};

  const entries = Object.entries(
    fieldErrors as Record<string, string[] | undefined>,
  );

  for (const [field, messages] of entries) {
    if (messages && messages.length > 0) result[field] = messages;
  }

  return result;
}

export async function createShipmentAction(
  input: ShipmentInput,
): Promise<ActionResult<Shipment>> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) return { success: false, error: UNAUTHORIZED_ERROR };

  const result = shipmentSchema.safeParse(input);

  if (!result.success) {
    return {
      success: false,
      error: INVALID_INPUT_ERROR,
      fieldErrors: toFieldErrors(result.error),
    };
  }

  const { reference, client_id, origin, destination, modality, status, eta } =
    result.data;

  // Only the writable business columns are sent. `id` and `created_at` are
  // database defaults and are never accepted from the caller. `.select()` asks
  // PostgREST to return the row it actually inserted, so the response carries
  // the server-generated `id` and `created_at` instead of an echo of the input.
  // `eta` is a Postgres `date`, which PostgREST accepts and returns as
  // `yyyy-mm-dd` — the same shape `shipmentSchema` validates, so no conversion
  // happens on either side.
  const { data, error } = await supabase
    .from("shipments")
    .insert({ reference, client_id, origin, destination, modality, status, eta })
    .select()
    .single();

  if (error) return { success: false, error: mutationError(error) };

  // `createClient()` in `src/lib/supabase/server.ts` is built without the
  // generated `Database` generic, so PostgREST types `data` as `any`. The row is
  // re-typed once, at this single boundary, so `any` never reaches
  // `ActionResult<Shipment>`.
  const persisted = data as Shipment;

  revalidatePath(SHIPMENTS_PATH);

  return { success: true, data: persisted };
}

export async function updateShipmentAction(
  input: ShipmentInput & { id: string },
): Promise<ActionResult<Shipment>> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) return { success: false, error: UNAUTHORIZED_ERROR };

  // Payload and id are validated independently so `shipmentSchema` keeps
  // describing the writable fields alone. `shipmentSchema` strips the extra `id`
  // key rather than rejecting it, so passing the whole input to both is safe.
  const body = shipmentSchema.safeParse(input);
  const target = shipmentIdSchema.safeParse(input);

  if (!body.success || !target.success) {
    return {
      success: false,
      error: INVALID_INPUT_ERROR,
      fieldErrors: {
        ...(body.success ? {} : toFieldErrors(body.error)),
        ...(target.success ? {} : toFieldErrors(target.error)),
      },
    };
  }

  const { reference, client_id, origin, destination, modality, status, eta } =
    body.data;

  // `created_at` is deliberately not in the update payload: it is the creation
  // timestamp and must survive an edit unchanged.
  const { data, error } = await supabase
    .from("shipments")
    .update({ reference, client_id, origin, destination, modality, status, eta })
    .eq("id", target.data.id)
    .select()
    .single();

  if (error) {
    // PGRST116 is PostgREST reporting that `.eq("id", ...)` selected zero rows,
    // which `.single()` turns into an error. That is a "the row is gone" answer,
    // not a transport failure: the shipment was deleted between render and
    // submit. Everything else is a real failure and gets its own message —
    // including the `23505` a reference collision and the `23503` a client that
    // no longer exists, which `mutationError` maps to dedicated copy.
    if (error.code === "PGRST116") {
      return { success: false, error: SHIPMENT_NOT_FOUND_ERROR };
    }

    return { success: false, error: mutationError(error) };
  }

  const persisted = data as Shipment;

  revalidatePath(SHIPMENTS_PATH);

  return { success: true, data: persisted };
}

export async function deleteShipmentAction(input: {
  id: string;
}): Promise<ActionResult<{ id: string }>> {
  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) return { success: false, error: UNAUTHORIZED_ERROR };

  // Deleting has no body to validate — only the row being targeted.
  const target = shipmentIdSchema.safeParse(input);

  if (!target.success) {
    return {
      success: false,
      error: INVALID_INPUT_ERROR,
      fieldErrors: toFieldErrors(target.error),
    };
  }

  // `.select("id")` is what makes "deleted one row" observable: without a
  // selection PostgREST returns `data: null`, so a delete that matched nothing
  // is indistinguishable from a successful one. With it, the response is the
  // array of rows that were actually removed and its length is the truth.
  const { data, error } = await supabase
    .from("shipments")
    .delete()
    .eq("id", target.data.id)
    .select("id");

  if (error) return { success: false, error: mutationError(error) };

  const deleted = (data ?? []) as { id: string }[];

  // Zero rows is not a success: reporting `success: true` here would tell the
  // UI a shipment was removed when nothing was. The row was deleted or hidden by
  // RLS after the list rendered.
  if (deleted.length === 0) {
    return { success: false, error: DELETE_NOT_FOUND_ERROR };
  }

  revalidatePath(SHIPMENTS_PATH);

  return { success: true, data: { id: deleted[0].id } };
}